output: dist
main:
  entry: src/main/main.ts
  output:
    directory: main
    filename: main.js
renderers:
  devPort: 8080
  entry: src/renderer/index.tsx
  html: src/renderer/index.html
  output:
    directory: renderer
    filename: renderer.js
  esbuild: electron-esbuild.renderer.config.js

