output: dist
main:
  entry: src/main/main.ts
  output:
    directory: main
    filename: main.js
renderers:
  entry: src/renderer/index.ts
  html: src/renderer/index.html
  devPort: 8080
  output:
    directory: renderer
    filename: renderer.js
